info:
  version: "@project.version@"
  component: Gateway service


spring:
  application:
    name: Gateway service
  cloud:
    config:
      name: Gateway service
      uri: http://localhost:31080 #to be changed
      fail-fast: true



zuul:
  routes:
    music:
      path: /artist/**
      serviceId: music


endpoints:
  restart:
    enabled: true
  shutdown:
    enabled: true
  health:
    enabled: true
    sensitive: true
server:
  port: 31080
eureka:
  client:
    enabled: true
    service-url:
      defaultZone: http://localhost:30080/eureka/




