spring:
  application:
    name: registry
  cloud:
    config:
      name: registry
      discovery:
        enabled: true
        service-id: registry


info:
  version: "@project.version@"
  name: "@project.name@"


endpoints:
  restart:
    enabled: true
  shutdown:
    enabled: true
  health:
    enabled: true
    sensitive: true


server:
  port: 30080
management:
  port: 30081


#THIS is EUREKA Server
eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://localhost:${server.port}/eureka/
  instance:
    metadataMap:
      management-url: http://${spring.cloud.client.hostname}:${management.port}
      management-port: ${management.port}
    leaseRenewalIntervalInSeconds: 10
    prefer-ip-address: true
    hostname: localhost
  server:
    waitTimeInMsWhenSyncEmpty: 0
